### ISSUE TITLE
Fix MUI Typography Bug

### ISSUE THREAD

**Issue by olivernjeru** [olivernjeru/replicant-trader#31]
Precursor. When a user clicks on the Account menu in the LoggedIn Navbar, an error appears in the console, something like this,
react-dom.development.js:86 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    at div
    at p
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Typography (http://localhost:3000/static/js/bundle.js:81811:87)
    at ul
    at http://localhost:3000/static/js/bundle.js:7007:66
    at List (http://localhost:3000/static/js/bundle.js:72868:82)
    at MenuList (http://localhost:3000/static/js/bundle.js:73429:7)
    at http://localhost:3000/static/js/bundle.js:7007:66
    at div
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Paper (http://localhost:3000/static/js/bundle.js:75359:83)
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Transition (http://localhost:3000/static/js/bundle.js:139904:30)
    at Grow (http://localhost:3000/static/js/bundle.js:69002:7)
    at FocusTrap (http://localhost:3000/static/js/bundle.js:60823:5)
    at div
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Portal (http://localhost:3000/static/js/bundle.js:61562:5)
    at Modal (http://localhost:3000/static/js/bundle.js:74102:82)
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Popover (http://localhost:3000/static/js/bundle.js:75603:83)
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Menu (http://localhost:3000/static/js/bundle.js:73726:83)
    at div
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Toolbar (http://localhost:3000/static/js/bundle.js:80777:82)
    at header
    at http://localhost:3000/static/js/bundle.js:7007:66
    at Paper (http://localhost:3000/static/js/bundle.js:75359:83)
    at http://localhost:3000/static/js/bundle.js:7007:66
    at AppBar (http://localhost:3000/static/js/bundle.js:62985:83)
    at LoggedIn (http://localhost:3000/static/js/bundle.js:4138:81)
    at div
    at LoggedInMainLayout (http://localhost:3000/static/js/bundle.js:5421:3)
    at div
    at MarketMakerDashboardPage
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:137692:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:138296:26)
    at PrivateRoutes (http://localhost:3000/static/js/bundle.js:435:74)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:137692:5)
    at Routes (http://localhost:3000/static/js/bundle.js:138383:5)
    at Router (http://localhost:3000/static/js/bundle.js:138317:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:136289:5)
    This is because of a MUI syntax bug

**Comment by olivernjeru** [comment]
- [ ] Fix MUI Typography Syntax Bug

**Comment by olivernjeru** [comment]
This is solved in [Fix Sign Out bug](https://github.com/olivernjeru/replicant-trader/commit/ba61e39d48ac48f0b78aea4a12791013e9288d1f)
